
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Abcd123@

mybatis:
  mapper-locations: classpath:/mapper/sample.xml